import { readFileSync } from "fs"
import { join } from "path"

/**
 * Brands the Medusa admin, including the pages no widget can reach.
 *
 * Medusa's extension points — widgets, custom routes, injection zones — all
 * live *inside* the authenticated dashboard. The login screen, the browser
 * title and the favicon are part of the packaged build and have no zone, which
 * is why the first attempt at this stopped at a header widget.
 *
 * The way in is `admin.vite` in medusa-config.ts, which hands us Vite's config
 * for the dashboard build. A plugin with `transformIndexHtml` can rewrite the
 * document shell that every admin page is served from, login included, without
 * forking the dashboard or patching node_modules.
 *
 * Kept outside `src/` deliberately: everything under `src/admin` is compiled
 * for the browser, and this is Node code that runs at build time.
 */

const BRAND = {
  name: "House of Sirka",
  /** Shown in the browser tab and when the admin is bookmarked. */
  title: "House of Sirka · Workroom",
  wine: "#8B1E3F",
  wineDark: "#6E1832",
  merlot: "#561026",
  ink: "#151413",
  inkSoft: "#4A443E",
  inkMuted: "#6E655C",
  paper: "#FFF9F1",
  pearl: "#FFFDF8",
  cream: "#F7EAD8",
  brass: "#F5DA9B",
  brassStrong: "#9C7129",
}

/**
 * The monogram, shared with the storefront rather than copied, so the mark in
 * the admin cannot drift from the mark on the shop.
 */
function monogram(): string {
  const path = join(__dirname, "../storefront/public/house-of-sirka-mark.svg")
  return readFileSync(path, "utf-8")
}

/** Inline SVG for use in CSS `url()`. Percent-encoded, not base64 — smaller and legible in devtools. */
function cssUrl(svg: string): string {
  const oneLine = svg.replace(/\s+/g, " ").trim()
  return `url("data:image/svg+xml,${encodeURIComponent(oneLine)}")`
}

/**
 * The token overrides.
 *
 * The dashboard is built on design tokens rather than hardcoded colours, so
 * rebranding means overriding the tokens once instead of chasing class names
 * through a compiled bundle. It is also what makes this survive upgrades: a
 * Medusa release can restructure its markup freely and these still apply.
 */
const TOKENS: Record<string, string> = {
  "bg-base": BRAND.pearl,
  "bg-base-hover": BRAND.paper,
  "bg-base-pressed": BRAND.cream,
  "bg-subtle": BRAND.paper,
  "bg-subtle-hover": BRAND.cream,
  "bg-subtle-pressed": BRAND.cream,
  "bg-component": BRAND.pearl,
  "bg-field": BRAND.pearl,
  "bg-field-hover": BRAND.paper,

  "fg-base": BRAND.ink,
  "fg-subtle": BRAND.inkSoft,
  "fg-muted": BRAND.inkMuted,
  "fg-on-color": "#ffffff",
  "fg-interactive": BRAND.wine,
  "fg-interactive-hover": BRAND.wineDark,

  "border-base": BRAND.brass,
  "border-strong": BRAND.brassStrong,
  "border-interactive": BRAND.wine,

  // The primary button, which is "inverted" in Medusa's vocabulary.
  "button-inverted": BRAND.wine,
  "button-inverted-hover": BRAND.wineDark,
  "button-inverted-pressed": BRAND.merlot,

  "contrast-bg-base": BRAND.merlot,
  "contrast-bg-base-hover": BRAND.wineDark,
  "contrast-bg-base-pressed": BRAND.wine,
  "contrast-bg-subtle": BRAND.merlot,
  "contrast-fg-primary": "#ffffff",

  "focus-border": BRAND.wine,
}

function brandCss(): string {
  const mark = cssUrl(monogram())

  /*
    `!important` on every token, which is not the usual reflex.

    Our <style> is injected into the document head at build time; the
    dashboard's own styles arrive after it — as a linked stylesheet in
    production, and injected by the dev server at runtime in development.
    Same specificity, later wins, so without this the overrides are simply
    ignored: measured on the running login page, --bg-subtle was still
    rgba(250,250,250,1) and the primary button still near-black.

    Ordering cannot be fixed from here without owning the document, so
    precedence is the honest lever. It is confined to custom properties, which
    nothing in the dashboard sets inline.
  */
  const tokens = Object.entries(TOKENS)
    .map(([name, value]) => `  --${name}: ${value} !important;`)
    .join("\n")

  return `
/* House of Sirka — admin branding. Generated by admin-brand.ts. */

:root,
.light {
${tokens}
}

/*
  The Medusa mark on the signed-out pages.

  It is rendered inline, has no configuration and no widget zone, so the svg is
  hidden and the box around it carries ours instead — at the size the dashboard
  already reserves, so nothing reflows.

  Matched on viewBox rather than class. There are two of these and they are
  different components: login draws the 400x400 mark inside an AvatarBox,
  reset-password draws a 36x38 hexagon in a plain logo box. Targeting the first
  one's Tailwind class left the second untouched, which is how the reset screen
  kept showing a wine-tinted Medusa hexagon. A viewBox is also the more durable
  hook — it describes the artwork, where an arbitrary-value class is an artefact
  of how the artwork happened to be styled.
*/
svg[viewBox="0 0 400 400"],
svg[viewBox="0 0 36 38"] {
  visibility: hidden;
}
div:has(> svg[viewBox="0 0 400 400"]),
div:has(> svg[viewBox="0 0 36 38"]) {
  background-image: ${mark};
  background-repeat: no-repeat;
  background-position: center;
  background-size: 76%;
  background-color: ${BRAND.paper} !important;
  border: 1px solid ${BRAND.brass};
  box-shadow: none !important;
}

/*
  Login and reset-password sit on the subtle background. Given the whole page is
  one card on an empty field, it is worth the warmth — this is the first thing
  anyone opening the admin sees, and a plain white field reads like scaffolding.
*/
body {
  background-color: ${BRAND.paper};
}

/*
  Form controls get the stronger brass rather than the divider weight.

  --border-base carries both dividers and input outlines. At brass-200 the
  divider is right and the input is not: measured 1.30:1 against the page, well
  under the 3:1 WCAG 2.2 asks for a control whose border is the only thing
  telling you it is a control (SC 1.4.11). Medusa's own default fails the same
  test at roughly 1.2:1, so this is not a regression introduced by rebranding —
  but it is worth fixing while the shop's own colours are going in, since the
  people typing into these fields will be doing it every day.
*/
input,
textarea,
select {
  border-color: ${BRAND.brassStrong} !important;
}
`.trim()
}

/**
 * Keeps the browser tab on-brand.
 *
 * The dashboard builds its title as `${pageTitle} - Medusa`, with the suffix
 * written into the compiled bundle — not a translation key and not
 * configurable, so overriding `login.title` alone still leaves "- Medusa" in
 * the tab and in every bookmark. This watches the title element and rewrites
 * the suffix as the router changes pages.
 *
 * A MutationObserver rather than a timer: it fires on the change itself, so
 * there is no window in which the wrong title is visible and nothing runs while
 * the tab sits idle.
 */
function titleScript(): string {
  return `
(function () {
  var SUFFIX = " · ${BRAND.name}";
  var MEDUSA_SUFFIX = " - Medusa";
  function brand() {
    var t = document.title;
    if (t.endsWith(SUFFIX) || t === "${BRAND.title}") return;
    if (t.endsWith(MEDUSA_SUFFIX)) {
      var page = t.slice(0, -MEDUSA_SUFFIX.length);
      // The login page's own heading is already the shop name, so appending it
      // again reads "House of Sirka · House of Sirka".
      document.title = page === "${BRAND.name}" ? "${BRAND.title}" : page + SUFFIX;
    } else if (t === "Medusa" || t === "Medusa Admin") {
      document.title = "${BRAND.title}";
    }
  }
  brand();
  var el = document.querySelector("title");
  if (el) new MutationObserver(brand).observe(el, { childList: true });
})();
`.trim()
}

/**
 * @returns a Vite plugin. Typed loosely on purpose: importing Vite's types into
 * medusa-config.ts would drag a build-time dependency into the runtime config,
 * and the shape used here is one well-established hook.
 */
/**
 * The storefront the admin links out to.
 *
 * Read at build time and inlined, because the admin is a static bundle with no
 * server to ask. Hardcoding localhost meant the "View the storefront" button
 * worked on one laptop and 404ed for everyone else.
 */
export const STOREFRONT_URL_GLOBAL = "__SIRKA_STOREFRONT_URL__"

export function houseOfSirkaAdminBrand() {
  const css = brandCss()
  const icon = `data:image/svg+xml,${encodeURIComponent(monogram().replace(/\s+/g, " ").trim())}`

  return {
    name: "house-of-sirka-admin-brand",
    transformIndexHtml(html: string) {
      return (
        html
          // The shell ships a blank placeholder icon the app swaps at runtime.
          // Replacing it in place rather than appending a second <link>, so
          // there is only ever one favicon to reason about.
          .replace(/<link rel="icon"[^>]*data-placeholder-favicon[^>]*\/?>/, `<link rel="icon" href="${icon}" />`)
          .replace(
            "</head>",
            `<title>${BRAND.title}</title>\n` +
              `<style id="house-of-sirka-brand">${css}</style>\n` +
              `<script>${titleScript()}</script>\n` +
              `</head>`,
          )
      )
    },
  }
}
